// these types were generated by ChatGPT by using the endpoint responses 😊

export interface Child {
  childId: string;
  institutionId: string;
  groupId: string;
  createdTime: string;
  name: {
    fullName: string;
    firstName: string;
    middleName: string;
    lastName: string;
  };
  birthday: string | null;
  homeAddress: string | null;
  extraInfo: string;
  language: string;
  nationality: string;
  birthplace: string;
  gender: number;
  startDate: string;
  endDate: string | null;
  leavingReason: string | null;
  isTestChild: boolean;
  image: {
    small: string;
    large: string;
    empty: boolean;
    colorCode: number;
  };
  isSleeping: boolean;
  hasVacation: boolean;
  isSick: boolean;
  isAbsent: boolean;
  onBus: boolean;
  onTrip: boolean;
  checkins: Checkin[];
  checkedIn: boolean;
  checkinTime: string | null;
  pickupTime: string | null;
  pickupRelationId: string;
  pickupName: string;
}

export interface Checkin {
  childCheckinId: string;
  childId: string;
  institutionId: string;
  groupId: string;
  checkinTime: string;
  pickupTime: string;
  pickupRelationId: string;
  goHomeWithChildId: string;
  checkoutTime: string | null;
  checkinLoginId: string;
  checkoutLoginId: string | null;
  autoCheckedOut: boolean;
  deletedAt: string | null;
  hours: number | null;
}
